/* 
ETE PD - AD 
PROFESSOR: CLOVES ROCHA 
CRUD EM C# - Comandos SQL (Server) para criação do banco de dados e tabela 
*/

/* CRIAR BANCO DE DADOS */
CREATE DATABASE BDCADASTRO

/* SELECIONA O BANCO DE DADOS */
USE BDCADASTRO

/* CRIACÇÃO DA TABELA */
CREATE TABLE CLIENTE (
      ID INT NOT NULL IDENTITY,
      NOME VARCHAR(50)  NOT NULL,
      ENDERECO VARCHAR(50),
      CEP VARCHAR(9),
      BAIRRO VARCHAR(50),
      CIDADE VARCHAR(50),
      UF VARCHAR(2),
      TELEFONE VARCHAR(15),
      CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
)
